### ISSUE TITLE
[Issue] ContextMenu를 개선해요

### ISSUE THREAD

**Issue by seungyooooong** [TeamND/Daily#104]
### 📝 이슈 요약
- 현재 RecordList에 적용되어있는 ContextMenu는 접근성이 좋지 않으며 일부 이슈가 있어요. 이를 개선해요

### ✅ TODOs
- [ ] 버튼 또는 Menu 방식으로 수정할 수 있는 방법을 찾아봐요 (RecordButton action과 중복여부 확인)
- [ ] 수정해 이슈를 개선해요
- [ ] 롱탭 & 드래그 타이밍 이슈를 확인하고 개선 여부를 판단해요

### 🧐 추가 설명
- 접근성이 떨어지는 롱탭 액션을 개선해요
- RecordButton action과 중복되지 않도록 주의하며 개선해요
- 롱탭 & 드래그 타이밍 이슈를 확인해요
