### ISSUE TITLE
[Issue] 튜토리얼 기능을 구현해요

### ISSUE THREAD

**Issue by seungyooooong** [TeamND/Daily#80]
### 📝 이슈 요약
- 튜토리얼 기능을 구현해요

### ✅ TODOs
- [ ] todo ex) 비즈니스 로직 구현
- [ ] todo ex) API 연동
- [ ] todo ex) 백그라운드 모드 설정

### 🧐 추가 설명
- additional description ex) viewModel을 분리해 구현해요
