### ISSUE TITLE
[Issue] 기능 단위로 폴더링을 수정해요

### ISSUE THREAD

**Issue by seungyooooong** [TeamND/Daily#81]
### 📝 이슈 요약
- Model, View, ViewModel을 기능 단위로 폴더링을 수정해요
- MVVM + Clean Architecture 폴더 구조를 지향해요

### ✅ TODOs
- [x] Extension 폴더 네이밍 방식을 수정해요
- [x] Assets color 네이밍 방식을 수정하고 폴더링해요
- [x] Clean Architecture 구조로 폴더링 방식을 수정해요

### 🧐 추가 설명
- 앞으로의 리팩토링 작업을 하기 전 폴더링 변경 작업을 위한 이슈에요
- 다음 이슈에서 extension에 불필요한 함수, 변수들 enum의 property로 수정해요
