### ISSUE TITLE
[Issue] UserInfoViewModel를 UserDefault로 수정해요

### ISSUE THREAD

**Issue by seungyooooong** [TeamND/Daily#83]
### 📝 이슈 요약
- UserInfoViewModel에 저장하던 정보들을 UserDefault로 옮겨요

### ✅ TODOs
- [x] UserDefaultManager를 생성해요
- [x] UserInfoViewModel의 데이터를 옮겨요
- [ ] View마다 AppStorage를 활용해 적용해요
- [x] get, set 로직을 수정해요

### 🧐 추가 설명
- 기존에 서버에서 저장하던 정보들을 비휘발 메모리인 UserDefault로 옮기는 작업이에요
- 더이상 서버에서 유저마다의 설정을 저장할 필요가 없어져요
