### ISSUE TITLE
[Issue] 새로운 아키텍처에 맞는 ViewModel을 만들어요

### ISSUE THREAD

**Issue by seungyooooong** [TeamND/Daily#93]
### 📝 이슈 요약
- DailyCalendarViewModel을 만들어요
- DailyGoalViewModel을 만들어요

### ✅ TODOs
- [x] CleanArchitecture 구조에 맞는 DailyCalendarViewModel을 만들어요
- [x] CleanArchitecture 구조에 맞는 DailyGoalViewModel을 만들어요
- [x] 새 Network layer를 통해 API를 연동해요
- [x] DailyRecordViewModel을 만들어요

### 🧐 추가 설명
- MVVM + CleanArchitecture를 리팩토링한 UI & Component에 적용시키는 과정이에요
- 새 Network layer가 적용될 예정이에요 (추후 SwiftData를 적용시키기 위한 초석이 될 수 있어요)
